apiVersion: v1
kind: Service
metadata:
  name: backend-despachos-service
  namespace: despachos-prod
  labels:
    app: backend-despachos
spec:
  type: ClusterIP
  selector:
    app: backend-despachos
  ports:
    - name: http
      port: 8081
      targetPort: 8081
